name: CAD Gallery

permissions:
  contents: write
  pages: write
  id-token: write
  packages: read

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build Gallery
        uses: ./
        with:
          use-docker: 'true'
          send-ping: 'true'

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./gallery

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v5
